drop database rio;
create database rio;
drop database rio_test;
create database rio_test;

use rio;
insert into tenants (email) values ('john.doe@gmail.com');
insert into tenants (email) values ('jane.doe@gmail.com');
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Peter", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "James", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Wendy", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Carrie", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Steve", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Jenny", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Sadie", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "David", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Clara", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Josh", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Nonnie", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Bob", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Carolyn", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Oscar", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Rosalie", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Julie", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Stewart", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Ella", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Evan", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Tommy", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Sara", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Emma", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Lindsay", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Brendon", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Ed", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Sandy", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Jeff", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Joe", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Bart", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Bruce", "blah", false);
insert into agents (tenant_id, available, engaged, display_name, encrypted_password, admin) values (1, true, false, "Sammy", "blah", false);
