#!/usr/bin/env ruby

require File.expand_path(File.dirname(__FILE__) + "/../config/environment")

begin
  messages = []
  begin
    messages = Message.need_response(50)
    messages.each{|m|
      create(:message, tenant: m.tenant, conversation: m.conversation, agent: m.conversation.engaged_agent || random_agent(m))
    }
  end until messages.empty
  sleep(7)
end while true

def random_agent(m)
  agents = Agent.where(tenant: m.tenant).all
  agents[rand(agents.size)]
end